### ISSUE TITLE
Proposal: function to set O_NONBLOCK on stream

### ISSUE THREAD

**Issue by danielparks** [cloudhead/popol#5]
I suspect a lot of applications that need to poll will also need non-blocking streams. Otherwise, you can end up reading all of one stream before you get any output on other streams.

On the other hand, I could see this being out-of-scope for popol.

This is the code I'm using. I'm happy to submit it as a PR with docs, etc. if you’d like.

```rust
pub fn set_nonblock(fd: &dyn AsRawFd) -> io::Result<()> {
    let fd = fd.as_raw_fd();

    // SAFETY: required for FFI; shouldn’t break rust guarantees.
    match unsafe { libc::fcntl(fd, libc::F_SETFL, libc::O_NONBLOCK) } {
        0 => Ok(()),
        -1 => Err(io::Error::last_os_error()),
        other => panic!("fcntl returned {} instead of 0 or -1", other),
    }
}
```

**Comment by cloudhead** [comment]
True, although I'd expect most users to use the `socket2` library. Nonetheless I think it's a nice idea, so wouldn't be opposed. I'd make two small changes to the above function, to make it in line with how `socket2` does things:

1. Rename to `set_nonblocking`
2. Remove the `panic` and have it so anything other than `-1` is `Ok`.

Here's the code from socket2 for reference:
```rust

/// Helper macro to execute a system call that returns an `io::Result`.
macro_rules! syscall {
    ($fn: ident ( $($arg: expr),* $(,)* ) ) => {{
        #[allow(unused_unsafe)]
        let res = unsafe { libc::$fn($($arg, )*) };
        if res == -1 {
            Err(std::io::Error::last_os_error())
        } else {
            Ok(res)
        }
    }};
}
```

**Comment by danielparks** [comment]
Ah, I see. I’m not using sockets, I’m using pipes from a child process. Perhaps I should look into adding a method to `std::process`…

Otherwise, those both seem like good suggestions. Should have something for you in the next week.

**Comment by danielparks** [comment]
Ok, PR #6 submitted!
